version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_WS_URL=ws://localhost:4000/graphql/subscriptions
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    env_file:
      - server/.env
    # depends_on:
    #   - redis

    # redis:
    #   image: redis:7-alpine
    #   ports:
    #     - "6379:6379"
    #   volumes:
    #     - redis_data:/data

volumes:
  redis_data:
